# Generated by Django 4.0.2 on 2022-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='Low', max_length=50),
        ),
    ]
